### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'quote_plus'

### ISSUE THREAD

**Issue by jolespin** [marto1/youtube-mp3#1]
I am using Python 3.6 is that why I'm getting this error?

**Comment by marto1** [comment]
Hi,
Just ran it on Python 3.6.3 and added support for it in the latest commit.

On an important side note the script relies entirely  on youtube-mp3.org for converting and downloading. The service was recently shut down as noted here: http://www.dailymail.co.uk/sciencetech/article-4853772/YouTube-MP3-org-agrees-shut-sued.html . I am yet to find a back end as good as youtube-mp3.org to transition to to make the script functional again. As of now, however, **the script is not functional** and you'll get [Errno 111] Connection refused from the service.
